### ISSUE TITLE
Where to look?

### ISSUE THREAD

**Issue by eliabntt** [unr-arl/rovio_bsp#4]
Hi, I'm Elia Bonetto. I'm currently working in a project for autonomous navigation and I'd like to plug in your edited ROVIO framework. From what I've understood by reading your paper you simulate the new camera position (and the features in the new frame), the IMU readings and use this simulated information to get a covariance of next pose odometry. Sadly, I can't wrap up where this is in the code.

As I said I'd like to plug this into my project but I don't really grasp where I should submit the data to get this estimation.

**Comment by cynosure4sure** [comment]
Hi Elia!
To use this functionality you would want to use rovio_bsp_node instead of rovio_node as it extends all extra functionality on top of normal rovio. The main difference here is that the rovio_bsp_node allows for filter propagation for every IMU message as seen here [rovio_bsp_node](https://github.com/unr-arl/rovio_bsp/blob/32f975a057a07f9fe138ba0d21be3a6c18720abf/src/rovio_bsp_node.cpp#L100)

Next you should start looking into the code for the "bsp_rovio/propagate_filter_state" service in [rovio_node.hpp](https://github.com/unr-arl/rovio_bsp/blob/32f975a057a07f9fe138ba0d21be3a6c18720abf/include/rovio/RovioNode.hpp#L236). I think the functionality you are looking for is in the function callback of this service call [here](https://github.com/unr-arl/rovio_bsp/blob/32f975a057a07f9fe138ba0d21be3a6c18720abf/include/rovio/RovioNode.hpp#L606)
